# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
defaults:
    #scope: 
      #path: "assets/img"
    values:
      image: true
name: "Juunoco's Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
meta_description: "Juunoco  Devlog"
assets:
    cache: false
title: Juunoco's Blog
email: juunoco@gmail.com
description: >- 
    Keeping you updated with our latest designs and developments 
# this means to ignore newlines until "baseurl:" >- '<p> &copy; </p>'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://www.juunoco.github.io" 
# the base hostname & protocol for your site, e.g. http://example.com
twitter_username: juunoco1
github_username:  juunoco
facebook_username: juunoco

# Build settings
#markdown: kramdown
#theme: minima 
#other themes are not compatible with blogs, and will show up blank
#remote-theme: wowthemesnet/mediumish-theme-jekyll
#theme: mediumish-theme-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  
repository: juunoco.github.io/blog
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: #no space allowed in front of this, or will throw compilation error
#    - vendor
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
   - vendor/bundle/ #need to exclude this to prevent weird date error from compiled file
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge


